import "./globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";

import Header from "@/components/header";

const SpaceGrotesk = localFont({
  src: "./fonts/SpaceGrotesk-VariableFont_wght.ttf",
  variable: "--font-space-grotesk",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Positivus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${SpaceGrotesk.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
